SHEET_ID = "1aLNdHM0QSQkgTsyaa0pFuoTCf7eFE7qmXpPSrlnFJO0"

[gcp_service_account]
type = "service_account"
project_id = "my-proj-2-440510"
private_key_id = "40b0552cada0933802a7eef27d1bf3137c2e969e"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDqDceYOdgkQA9y
fq45nfytEvtxyo82yXzi58lgCG+hLrhfRI4d1hLJQSkZTHEJyOJPRFB16fRdKNS9
TzICa/Hx/RHethFtdMU4hjqootjll1sMTpapnoJPetEc4A6ubox0XTW4dzYYHouu
2aHj5BbFuRv/HJW8N6wPiJOySRB9/B/kIQSBT8NJCuNtyM71WRJ8JQQaC9hSfzYg
...
uJq2DTZhvwJ31WI7qls42A==
-----END PRIVATE KEY-----"""
client_email = "air-quality-bot@my-proj-2-440510.iam.gserviceaccount.com"
client_id = "103953394962517879648"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/air-quality-bot%40my-proj-2-440510.iam.gserviceaccount.com"
universe_domain = "googleapis.com"

