SHEET_ID = "1aLNdHM0QSQkgTsyaa0pFuoTCf7eFE7qmXpPSrlnFJO0"

[gcp_service_account]
type = "service_account"
project_id = "my-proj-2-440510"
private_key_id = "a37f500dfe8d4a0a25f9025611614eac32bf12be"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDQB7uGQRLPCti0
dGSYMZ6YyOd1Qn7Fnavn2ATdt90EXbsJk2cfpBBPybfpG1kz08IxDBYJc0+pgQf3
jureRy73f1Kz6KORs1vn2JvDFpKfXp0EA69w0OMbkEuxxvd/2FsXM+hE0wWrPA2y
UZwZJ5YdOvFBvCbUf/UIxgw/IfqH8HiFfAou9oz7jYid98CW3kIhQ/A331K1fnUO
8/bvL2TwbnL/Ey1IYvOaGdjyXetx7Tntz9g2j308bufit3ZHztPFhEaawrMTpX9B
VMQJZk0SxB4KByOaJHaIc9zuZ8fHkpr/LiYdxznJHdpZ2OfvCEzrfwibIr7fTyGA
6REOQcxrAgMBAAECggEADA85XJCJfcLJX43/G4rbgKGQ4rgj740dieH4x5Og4TUV
Inp5jW4uMI88ipZhHEMygYkLqVOWcs3olNN4+Ra+TxmsmoJUzR2ifnUM895rSd2A
aQWqViC93FCymqUyntDU2FT+1NKOLxLa+73bDeLrba6yOAHSFxqDLWrcYI013/XC
0oFTBqGtzynJTYtO4WhGMkTWPwyqmWi2GAqU1ajfznGd0jJ3KY1eQK56YJEF2O1O
yLW5VBFrn2TNn+zrv/XsbOsHAyU8qJ5yG2T66DRhaZKyK/3cQ6nPFmajd/GJgmHs
x49N7D8taDfcZVquhjcdOebcvMn49WC5CLQunQT80QKBgQDoJ79a/ncd/AeAWRfU
JRn511RWCcmfh5J3tEvtUPrc6OpC1e0Efc/48iFpM1AAMsM4UVkoKFv2F6U2mQs/
LZJhVKHTQEafVsAmniJB24yhQC/VPSzpGPCQGZY9+t4EvO13jDi3rIQhj/A2QQCt
QJpGsIlF/J+eAreILbH2HCjtkQKBgQDlZaUKvmSbmu+8gg/5EHGYoQ9n9vigEje3
ihI1SdxuHD3sXQPKymGT8xZRJr3LfXur90jO9BWyr46swfia0Kz5MhBr/z4E5pw7
Qgk9CvAI1kRLlX63VJnyQYNHsh6xcuFM/eiP+S2wqZPupz4ZLSgyYz/LM0qZgpnW
+XI/D4xMOwKBgQDJrxY/0Afd5cECkOPxqpXJhnc/E9u0mwv0sI6xygNWfYZesAjs
OPy/kmLSSQC8W11cBNgG2iEiR2KBby3lIgskQWkg5Js1/CCMrB6oxjqDMAceIrps
ev0qwv/SMqpExXkrvYbckqRrn+eYypny6cfdl6p6QcDNfiDBzqjnXYl08QKBgQDV
FRG1ZR13HPhLllTX+dpK+HCjFdnkdoeiyXIYZb+H2Fv8znnTSSJSl57HSsFJ4Amc
t1q+QiRVkpVpC9StmeDSqRpv9uvZCY1dzf1e4mYND1rpCrhl+wP0773OPzobgqad
Kc14zvEOBLcRG/Cm2jdYdrCvQ7mr1pCoC5V/1iVwOQKBgQC4cn05dhEH/F731jFt
/iOvsERird/x3dTSKb3n+geaQD3SfXDCeLrgJF9BISGANIrlE3tIjoZKtj98g4Yc
X50kF29jPgmWOy0BpT+f+bhW2N1i/ondopyQ/hyAy81bPfbGZbZJkyljEgLPrjiE
TG9RXlPk+APrlSOffmtndNwEXA==
-----END PRIVATE KEY-----"""
client_email = "air-quality-bottt@my-proj-2-440510.iam.gserviceaccount.com"
client_id = "103262185678474693777"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/air-quality-bottt%40my-proj-2-440510.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
